parameters:
#    shandong_opera_admin.example.class: Shandong\OperaAdminBundle\Example

services:
#    shandong_opera_admin.example:
#        class: %shandong_opera_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
